import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms — Meridian",
  description: "The terms of use for Meridian.",
};

export default function Terms() {
  return (
    <main className="mx-auto w-full max-w-3xl flex-1 px-6 py-16">
      <Link href="/" className="mono text-sm tracking-[0.2em] text-muted transition hover:text-foreground">
        <span className="text-accent glow">⊕</span> MERIDIAN
      </Link>
      <h1 className="mt-8 text-4xl font-bold">Terms of Use</h1>
      <p className="mt-2 text-sm text-muted">Last updated June 2026.</p>
      <div className="mt-8 space-y-5 leading-relaxed text-muted">
        <p>
          <span className="font-medium text-foreground">As-is, no warranty.</span> Meridian is provided free and
          &quot;as is,&quot; without warranties of any kind. We don&apos;t guarantee availability, accuracy, or fitness
          for a particular purpose.
        </p>
        <p>
          <span className="font-medium text-foreground">Automated analysis.</span> Findings are generated by AI agents
          and may be incomplete or wrong. Treat them as a starting point and apply your own judgment — don&apos;t rely
          on them as professional security, legal, or financial advice.
        </p>
        <p>
          <span className="font-medium text-foreground">Your responsibility.</span> Only submit content and credentials
          you&apos;re authorized to share. You&apos;re responsible for how you use the output.
        </p>
        <p>
          <span className="font-medium text-foreground">Limitation of liability.</span> To the maximum extent permitted
          by law, Meridian and its authors aren&apos;t liable for any damages arising from use of the tool or its output.
        </p>
      </div>
      <Link
        href="/"
        className="pill mt-10 inline-block border border-border px-5 py-2.5 text-sm text-muted transition hover:text-foreground"
      >
        ← Back to Meridian
      </Link>
    </main>
  );
}
